"""Quorix API — Claim, EvidenceSpan, and Citation models."""

from __future__ import annotations

import uuid
from typing import TYPE_CHECKING

from sqlalchemy import Float, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.infrastructure.database.base import Base, TimestampMixin, UUIDMixin

if TYPE_CHECKING:
    from app.infrastructure.database.models.conversation import Message
    from app.infrastructure.database.models.document import Document, DocumentChunk
    from app.infrastructure.database.models.paper import Paper


class Claim(Base, UUIDMixin, TimestampMixin):
    """An individual assertion generated by the assistant, subject to verification."""

    __tablename__ = "claims"

    message_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("messages.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    claim_text: Mapped[str] = mapped_column(Text, nullable=False)
    verification_state: Mapped[str] = mapped_column(
        String(30),
        default="unverified",
        nullable=False,
    )  # verified, partial, unverified, missing
    confidence: Mapped[float | None] = mapped_column(Float, nullable=True)
    order_index: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    message: Mapped[Message] = relationship("Message", back_populates="claims")
    evidence_spans: Mapped[list[EvidenceSpan]] = relationship(
        "EvidenceSpan",
        back_populates="claim",
        cascade="all, delete-orphan",
    )
    citations: Mapped[list[Citation]] = relationship(
        "Citation",
        back_populates="claim",
        cascade="all, delete-orphan",
    )


class EvidenceSpan(Base, UUIDMixin, TimestampMixin):
    """Specific excerpt / chunk from a paper or external source supporting or refuting a claim."""

    __tablename__ = "evidence_spans"

    claim_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("claims.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    chunk_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("document_chunks.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    paper_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("papers.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    document_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("documents.id", ondelete="SET NULL"),
        nullable=True,
    )
    page_number: Mapped[int | None] = mapped_column(Integer, nullable=True)
    section: Mapped[str | None] = mapped_column(String(200), nullable=True)
    evidence_text: Mapped[str] = mapped_column(Text, nullable=False)
    relevance_grade: Mapped[str | None] = mapped_column(
        String(30),
        nullable=True,
    )  # HIGH_RELEVANCE, PARTIAL_RELEVANCE, IRRELEVANT
    retrieval_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    reranker_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    grader_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    source_type: Mapped[str] = mapped_column(
        String(30),
        default="paper",
        nullable=False,
    )  # paper, external

    claim: Mapped[Claim] = relationship("Claim", back_populates="evidence_spans")
    chunk: Mapped[DocumentChunk | None] = relationship("DocumentChunk")
    paper: Mapped[Paper] = relationship("Paper")
    document: Mapped[Document | None] = relationship("Document")


class Citation(Base, UUIDMixin, TimestampMixin):
    """Formal citation linking a claim to its verified evidence and paper."""

    __tablename__ = "citations"

    claim_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("claims.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    evidence_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("evidence_spans.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    paper_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("papers.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    page_number: Mapped[int | None] = mapped_column(Integer, nullable=True)
    citation_text: Mapped[str | None] = mapped_column(String(500), nullable=True)

    claim: Mapped[Claim] = relationship("Claim", back_populates="citations")
    evidence: Mapped[EvidenceSpan] = relationship("EvidenceSpan")
    paper: Mapped[Paper] = relationship("Paper")
